services:
  db:
    image: postgres:17-alpine
    container_name: db_blog
    env_file:
      - ./backend/.env.prod
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - ./backend/.env.prod
    volumes:
      - ./backend/blog_project:/app/blog_project
      - ./backend/blog:/app/blog
      - static_data:/app/staticfiles
    environment:
      DB_HOST: db
    depends_on:
      - db
    restart: always

  frontend-builder:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
      - frontend_dist:/dist
    env_file:
      - ./frontend/.env.prod
    command: sh -c "npm ci && npm run build && cp -r dist/* /dist"
    restart: "no"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    env_file:
      - ./nginx/.env.prod
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend-builder
    volumes:
      - static_data:/app/staticfiles:ro
      - frontend_dist:/usr/share/nginx/html:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/log/nginx:/var/log/nginx
    restart: always

volumes:
  static_data:
  postgres_data:
  frontend_dist:
